name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest,${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:sha-${{ github.sha }}

      - name: Save short SHA
        id: short-sha
        run: echo "SHORT_SHA=latest" >> $GITHUB_ENV

      - name: Checkout infrastructure repository
        uses: actions/checkout@v3
        with:
          repository: TP1-OuterMSA/msa-infra
          path: msa-infra
          token: ${{ secrets.GH_PAT }}

      - name: Update image tag in Helm chart
        run: |
        cd msa-infra/charts/services/msa-test1
        sed -i "s/tag: \".*\"/tag: \"latest\"/g" values.yaml
          
      - name: Commit and push changes to infrastructure repo
        run: |
          cd msa-infra
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update msa-test1 image tag to sha-${SHORT_SHA}"
          git push
